/*
 * (C) Copyright 2007-2013
 * Allwinner Technology Co., Ltd. <www.allwinnertech.com>
 * mini_gui <liaoyongming@allwinnertech.com>
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

#ifndef _SUNXI_ADVERT_H_
#define _SUNXI_ADVERT_H_

#define ADVERT_MAGIC				"advert-group"
#define ADVERT_VERSION				"0100"

typedef struct __advert_head
{
	u8 magic[16];     //数据头标示 "advert-group"
	u8 version[4];      //"0100"
	u8 partname[16];  //partition name
	u32 check_sum;    //generated by android
	u32 length;		  //logo file length
	u8 filename[16];   //图片名字,固定名字advert.bmp
	u8 reserve[452];   //512-16-4-16-4-4-16 = 452
}_advert_head;

#endif
