obj-$(CONFIG_LCD_SUNXI) += lcd.o

lcd-objs := dev_lcd.o lcd_source_interface.o lcd_panel_cfg.o panels/panels.o panels/default_panel.o panels/tft720x1280.o\
            panels/vvx10f004b00.o panels/lp907qx.o panels/B116XAN03.o panels/gm7121_cvbs.o \
              
